### PR TITLE
Optimisations to run on macOS, and other ones

### PR DESCRIPTION
**Pull request by locness3**
Generally :
- The app is coded to quit when there's no more window, except on mac
- Added a drag zone 38px wide, I think, to the window

On Mac :
- If no window's open, and the dock icon is clicked, it opens a new app window (since app hasn't quit)

### CODE REVIEW

**Comment by locness3** [comment]
@kyleplo

**Comment by locness3** [comment]
> Looks good, but today I will be splitting this into three repositories: overcast (for the HTML, CSS and JavaScript), overcast-electron (for the electron app) and overcast-chrome (for a ChromeOS app)

You don't need a repo for html/css and one for electron app!
If you put your css and js files in src folder

**Comment by locness3** [comment]
Could I merge ?

**Comment by kyleplo** [comment]
Ok

**Pull request merged**
